
version: '2'

services:
  pg-master:
    build: '.'
    image: 'danieldent/postgres-replication'
    restart: 'always'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
     - '/var/lib/postgresql/data'
    expose:
     - '5432'

  pg-slave:
    build: '.'
    image: 'danieldent/postgres-replication'
    restart: 'always'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data/pgdata'
      PORT: '5433'
      REPLICATE_FROM: 'pg-master'
      REPLICATE_PORT: '5432'
    volumes:
     - '/var/lib/postgresql/data'
    expose:
     - '5433'
    links:
     - 'pg-master'
